export const COMPETITION_ITEMS = [
  { key: "argentina", label: "Liga Argentina", name: "Liga Profesional Argentina" },
  { key: "copa_argentina", label: "Copa Argentina", name: "Copa Argentina" },
  { key: "libertadores", label: "Libertadores", name: "CONMEBOL Copa Libertadores" },
  { key: "sudamericana", label: "Sudamericana", name: "CONMEBOL Copa Sudamericana" },
  { key: "champions", label: "Champions", name: "Champions League" },
  { key: "europa_league", label: "Europa League", name: "UEFA Europa League" },
  { key: "conference_league", label: "Conference", name: "UEFA Conference League" },
  { key: "primera_nacional", label: "Nacional", name: "Primera Nacional" },
  { key: "primera_b_metro", label: "B Metro", name: "Primera B Metropolitana" },
  { key: "primera_c", label: "Primera C", name: "Primera C" },
  { key: "reserva", label: "Reserva", name: "Torneo de Reserva" },
  { key: "colombia", label: "Colombia", name: "Liga BetPlay" },
  { key: "mls", label: "MLS", name: "Major League Soccer" },
  { key: "nations_league", label: "Nations L.", name: "UEFA Nations League" },
  { key: "paraguay", label: "Paraguay", name: "Copa de Primera (Paraguay)" },
  { key: "mexico", label: "México", name: "Liga MX" },
  { key: "brasil", label: "Brasil", name: "Brasileirao" },
  { key: "chile", label: "Chile", name: "Liga de Primera (Chile)" },
  { key: "uruguay", label: "Uruguay", name: "Liga AUF Uruguaya" },
  { key: "premier_league", label: "Premier", name: "Premier League" },
  { key: "efl_cup", label: "EFL Cup", name: "EFL Cup" },
  { key: "fa_cup", label: "FA Cup", name: "FA Cup" },
  { key: "laliga", label: "LaLiga", name: "LaLiga" },
  { key: "copa_del_rey", label: "Copa del Rey", name: "Copa del Rey" },
  { key: "supercopa_espana", label: "Supercopa ESP", name: "Supercopa de España" },
  { key: "serie_a", label: "Serie A", name: "Serie A" },
  { key: "coppa_italia", label: "Coppa Italia", name: "Coppa Italia" },
  { key: "supercoppa_italiana", label: "Supercoppa ITA", name: "Supercoppa Italiana" },
  { key: "bundesliga", label: "Bundesliga", name: "Bundesliga" },
  { key: "dfb_pokal", label: "DFB Pokal", name: "DFB Pokal" },
  { key: "liga_portugal", label: "Liga Portugal", name: "Liga Portugal" },
  { key: "ligue_1", label: "Ligue 1", name: "Ligue 1" },
  { key: "coupe_de_france", label: "Coupe de France", name: "Coupe de France" },
  { key: "u20_world_cup", label: "Mundial Sub-20", name: "Mundial Sub-20" },
  { key: "copa_america", label: "Copa América", name: "Copa América" },
  { key: "eliminatorias_conmebol", label: "Elim. CONMEBOL", name: "Eliminatorias CONMEBOL" },
  { key: "eliminatorias_uefa", label: "Elim. UEFA", name: "Eliminatorias UEFA" },
  { key: "eliminatorias_concacaf", label: "Elim. CONCACAF", name: "Eliminatorias CONCACAF" },
  { key: "euro", label: "Eurocopa", name: "Eurocopa" },
  { key: "repechaje_mundial", label: "Repechaje", name: "Repechaje Mundial" },
];
